[package]
name = "dg_fast_farmer"
version = "1.0.1"
edition = "2021"
authors = ["James Hoerr"]
description = "A lite farmer for the Chia Blockchain."
license = "Apache-2.0"
homepage = "https://github.com/GalactechsLLC/dg_fast_farmer"
repository = "https://github.com/GalactechsLLC/dg_fast_farmer"

[[bin]]
name="ff"
path="src/main.rs"

[profile.release]
codegen-units = 1
lto = "fat"

[dependencies]
async-trait = "0.1.77"
bip39 = {version= "2.0.0", features=["rand"] }
blst = "0.3.7"
bytefmt = "0.1.7"
clap = { version = "4.5.1", features = ["derive"] }
chrono = "0.4.34"
crossterm = "0.27.0"
dialoguer = "0.11.0"
dg_xch_cli = { version= "2.0.2" }
dg_xch_clients = { version= "2.0.2" }
dg_xch_core = { version = "2.0.2", features = ["paperclip"] }
dg_xch_keys = { version= "2.0.2" }
dg_xch_macros = { version= "2.0.2" }
dg_xch_pos = { version= "2.0.2" }
dg_xch_puzzles = { version= "2.0.2" }
dg_xch_serialize = { version= "2.0.2" }
futures-util = "0.3.29"
hex = "0.4.3"
home = "0.5.9"
log = "0.4.20"
once_cell = "1.19.0"
rand = { version = "0.8.5", features = [] }
ratatui = "0.26.1"
reqwest = {version="0.11.24", default-features = false, features =["rustls-tls", "json"]}
serde = {version="1.0.197", features = ["derive"]}
serde_json = "1.0.114"
serde_yaml = "0.9.32"
simple_logger = "4.3.3"
sysinfo = "0.30.5"
tokio = {version = "1.36.0", features=["rt-multi-thread", "sync", "signal", "macros", "process", "time", "fs", "net"]}
tokio-tungstenite = {version = "0.20.1", features = ["rustls-tls-webpki-roots", "rustls"] }
tui-logger = {version = "0.11.0"}
uuid = {version="1.7.0", features=["v4"]}

[build-dependencies]
bindgen = "0.69.4"