[package]
name = "dg_fast_farmer"
version = "1.0.1"
edition = "2021"
authors = ["James Hoerr"]
description = "A lite farmer for the Chia Blockchain."

[[bin]]
name="ff"
path="src/main.rs"

[dependencies]
async-trait = "0.1.74"
blst = "0.3.11"
dialoguer = "0.11.0"
dg_xch_cli = { version="1.1.2" }
dg_xch_clients = { version="1.1.2" }
dg_xch_core = { version = "1.1.2", features = ["paperclip"] }
dg_xch_keys = { version="1.1.2" }
dg_xch_macros = { version="1.1.2" }
dg_xch_pos = { version="1.1.2" }
dg_xch_puzzles = { version="1.1.2" }
dg_xch_serialize = { version="1.1.2" }
futures-util = "0.3.29"
hex = "0.4.3"
hyper-tungstenite = "0.11.1"
log = "0.4.20"
once_cell = "1.18.0"
reqwest = {version="0.11.22", features =["rustls-tls", "json"]}
serde = {version="1.0.192", features = ["derive"]}
serde_json = "1.0.108"
serde_yaml = "0.9.27"
simple_logger = "4.2.0"
tokio = {version = "1.34.0", features=["rt-multi-thread", "sync", "signal", "macros", "process", "time", "fs", "net"]}
tokio-tungstenite = {version = "0.20.1", features = ["rustls-tls-webpki-roots", "rustls"] }
uuid = {version="1.5.0", features=["v4"]}
home = "0.5.5"
clap = { version = "4.4.8", features = ["derive"] }
crossterm = "0.25"
tui = "0.19"
tui-logger = {version = "0.10.0"}
bytefmt = "0.1.7"
sysinfo = "0.29.2"
ratatui = "0.24.0"
chrono = "0.4.31"