on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install latest Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.85.0
          default: true
          override: true
          components: rustfmt, clippy
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Run Format
        run: cargo fmt --all -- --check
      - name: Run Clippy
        run: cargo clippy -- -Dwarnings
  build:
    name: Build
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            package-suffix: ubuntu
            binary-name: ff
          - os: macos-latest
            package-suffix: macos
            binary-name: ff
          - os: windows-latest
            package-suffix: windows
            binary-name: ff.exe
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install latest Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.85.0
          default: true
          override: true
          components: rustfmt, clippy
      - name: Build binary
        run: cargo build --release
      - name: Save release archive
        uses: actions/upload-artifact@v4
        with:
          name: ff-x86_64-${{ matrix.package-suffix }}
          path: target/release/${{ matrix.binary-name }}
