name: Build tests

on:
  push:
    branches: '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on:
      - ubuntu-latest
    if: github.event_name == 'push'

    name: Check format
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Run Format
        run: cargo fmt --all -- --check

  clippy:
    runs-on:
      - ubuntu-latest
    if: github.event_name == 'push'

    name: Run clippy
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Run Clippy
        run: cargo clippy -- -Dwarnings